name: Update Github README.md
on:
    schedule:
        -   cron: '42 0 * * *'
    workflow_dispatch: ~

jobs:
    update:
        name: Re Generate README.md
        runs-on: ubuntu-latest
        env:
            CRYSTALLIZE_TENANT_IDENTIFIER: ${{ secrets.TENANT_IDENTIFIER }}
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v3

            - name: ⎔ Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: 📥 Download deps
              run: yarn install

            - name: 🏄 Run the build
              run: yarn build

            - name: 📢 Generate the file
              run:  node build/index.js > profile/README.md
            
            - name: 🍿 Commit and push if changed
              run: |
                git diff
                git config --global user.email "hello@crystallize.com"
                git config --global user.name "CrystallizeAPI"
                git commit -am "Auto-Update Readme"
                git push
